Finacial-Portal/Controllers/HomeController.cs
using Finacial_Portal.Helpers;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Finacial_Portal.Controllers
{
    public class HomeController : Controller
    {
        UserHelper userHelper = new UserHelper();
        [Authorize]
        public ActionResult Index()
        {
            var userId = User.Identity.GetUserId();
            var hhId = UserHelper.GetHouseholdId();

            switch (hhId)
            {
                case -1:
                    return RedirectToAction("Lobby", "Home");
                default:
                    break;
            }

            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }

        [Authorize]
        public ActionResult Lobby()
        {
            return View();
        }
    }
}

Finacial-Portal/Controllers/MorrisController.cs
using Finacial_Portal.Models;
using Finacial_Portal.ViewModels;
using Microsoft.AspNet.Identity;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Finacial_Portal.Controllers
{
    public class MorrisController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        [Authorize]
        public ActionResult GetBudgetDataForBarChart()
        {
            var budgetData = new List<MorrisBudgetBar>();

            var userId = User.Identity.GetUserId();

            var houseId = db.Users.Find(userId).HouseholdId;
            if (houseId == null)
                return Content(JsonConvert.SerializeObject(budgetData), "application/json");

            foreach (var budget in db.Households.Find(houseId).Budgets.ToList())
            {
                budgetData.Add(new MorrisBudgetBar
                {
                    Label = budget.Name,
                    Target = budget.Target,
                    Actual = budget.CurrentBalance
                });
            }

            return Content(JsonConvert.SerializeObject(budgetData), "application/json");
        }
    }
}

Finacial-Portal/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Finacial-Portal/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Finacial-Portal/Views/Home/Index.cshtml
@using Finacial_Portal.Models
@using Microsoft.AspNet.Identity

@{ 
    var db = new ApplicationDbContext();
    var userId = User.Identity.GetUserId();
    var userhhId = db.Users.Find(userId).HouseholdId;
    var hhAccounts = db.Households.Find(userhhId).Accounts;

    var userBudgets = db.Budgets.Where(h => h.HouseholdId == userhhId);
    var userTransactions = db.Transactions.Where(u => u.EnteredById == userId);
}


<div class="block-header">
    <h2>DASHBOARD</h2>
</div>

<!-- Widgets -->
<div class="row clearfix">
    <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12">
        <div class="info-box bg-cyan hover-expand-effect">
            <div class="icon">
                <i class="material-icons">dock</i>
            </div>
            <div class="content">
                <div class="text">BUDGETS</div>
                <div class="number count-to" data-from="0" data-to="@userBudgets.Count()" data-speed="1000" data-fresh-interval="20"></div>
            </div>
        </div>
    </div>
    <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12">
        <div class="info-box bg-orange hover-expand-effect">
            <div class="icon">
                <i class="material-icons">monetization_on</i>
            </div>
            <div class="content">
                <div class="text">TRANSACTIONS</div>
                <div class="number count-to" data-from="0" data-to="@userTransactions.Count()" data-speed="1000" data-fresh-interval="20"></div>
            </div>
        </div>
    </div>
    <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12">
        <div class="info-box bg-pink hover-expand-effect">
            <div class="icon">
                <i class="fas fa-piggy-bank material-icons"></i>
            </div>
            <div class="content">
                <div class="text">BANK ACCOUNTS</div>
                <div class="number count-to" data-from="0" data-to="@hhAccounts.Count()" data-speed="1000" data-fresh-interval="20"></div>
            </div>
        </div>
    </div>
</div>
<!-- #END# Widgets -->

<div class="row clearfix">
    <!-- Visitors -->
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
        <div class="card">
            @if (userBudgets.Count() >= 1)
            {
                <div class="body custom">
                    <div id="budgetChart"></div>
                </div>
            }
            else
            {
                <div class="body custom">
                    <div class="font-45 text-center">There is no budget data to display</div>
                </div>
            }

        </div>
    </div>
    <!-- #END# Visitors -->
</div>

<div class="row clearfix">
    <!-- Task Info -->
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
        <div class="card custom-t">
            <div class="header">
                <h2>Transactions</h2>
            </div>
            <div class="body">
                <div class="table-responsive">
                    @Html.Partial("_TransactionsTable")
                </div>
            </div>
        </div>
    </div>
    <!-- #END# Task Info -->
</div>

@section scripts{

    <script>
        $.post('@Url.Action("GetBudgetDataForBarChart", "Morris")').then
            (function (response) {
                new Morris.Bar({
                    element: 'budgetChart',
                    data: response,
                    xkey: 'Label',
                    ykeys: ['Target', 'Actual'],
                    labels: ['Target', 'Actual'],
                    //xLabelAngle: 45,
                    gridTextColor: '#555',
                    barColors: ['#59c0ff', '#f681e0'],
                    preUnits: '$'
                })
            })
    </script>
    
    <script>
        $('.table').DataTable();
    </script>
}

Finacial-Portal/Views/Home/Lobby.cshtml
@using Finacial_Portal.Helpers
@using Microsoft.AspNet.Identity
@using Finacial_Portal.Models

@{ 
    var userId = User.Identity.GetUserId();
    UserHelper userHelper = new UserHelper();
}

<style>
    .member {
        padding-top: 15px;
        padding-bottom: 15px;
    }
</style>

<div class="card">
    <div class="header">
        Lobby
    </div>
    <div class="body">
        <div class="row">
            @foreach (var user in userHelper.UsersNotInHouse())
            {
                if (user.Id == userId)
                {
                    <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
                        <div class="info-box bg-blue hover-expand-effect">
                            <div class="icon">
                                <img class="member" src="@UserHelper.GetAvatarPath(user.Id)" width="50" height="80" alt="User" />
                            </div>

                            <div class="content">
                                <div class="text small">YOU</div>
                                <div class="number">
                                    @user.FirstName @user.LastName
                                </div>
                            </div>
                        </div>

                    </div>
                }
                else
                {
                    <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
                        <div class="info-box bg-blue hover-expand-effect">
                            <div class="icon">
                                <img class="member" src="@UserHelper.GetAvatarPath(user.Id)" width="50" height="80" alt="User" />
                            </div>

                            <div class="content">
                                <div class="number">
                                    @user.FirstName @user.LastName
                                </div>
                            </div>
                        </div>

                    </div>
                }
                
            }
        </div>
    </div>
</div>